### ISSUE TITLE
Show time/rounds left

### ISSUE THREAD

**Issue by dolthead** [walkingriver/we-spot#18]
Still not sure if it's a timed game or an X-number-of-rounds game. Either way, show the time or rounds left. And if the latter, show the total elapsed time. From nikellester@simplybest.com

**Comment by walkingriver** [comment]
I added a "cards remaining" indicator last night. Check it out and let me know whether that is what you had in mind.

**Comment by dolthead** [comment]
@walkingriver That does the trick, thanks!

**Comment by walkingriver** [comment]
Closing issue, then. Thanks!
